export const ErrorCode = {
  // Auth errors
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  INVALID_TOKEN: "INVALID_TOKEN",
  INVALID_OTP: "INVALID_OTP",
  OTP_EXPIRED: "OTP_EXPIRED",
  PASSKEY_VERIFICATION_FAILED: "PASSKEY_VERIFICATION_FAILED",
  SESSION_EXPIRED: "SESSION_EXPIRED",

  // Validation errors
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_INPUT: "INVALID_INPUT",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",

  // Resource errors
  NOT_FOUND: "NOT_FOUND",
  ENTERPRISE_NOT_FOUND: "ENTERPRISE_NOT_FOUND",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  ACCOUNT_NOT_FOUND: "ACCOUNT_NOT_FOUND",
  APPROVAL_NOT_FOUND: "APPROVAL_NOT_FOUND",

  // Business logic errors
  KYB_PENDING: "KYB_PENDING",
  KYB_REJECTED: "KYB_REJECTED",
  INSUFFICIENT_FUNDS: "INSUFFICIENT_FUNDS",
  LIMIT_EXCEEDED: "LIMIT_EXCEEDED",
  APPROVAL_REQUIRED: "APPROVAL_REQUIRED",
  APPROVAL_ALREADY_VOTED: "APPROVAL_ALREADY_VOTED",
  APPROVAL_EXPIRED: "APPROVAL_EXPIRED",
  ADDRESS_NOT_WHITELISTED: "ADDRESS_NOT_WHITELISTED",
  STRATEGY_PAUSED: "STRATEGY_PAUSED",
  IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT",

  // System errors
  INTERNAL_ERROR: "INTERNAL_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  DATABASE_ERROR: "DATABASE_ERROR",
  CHAIN_ERROR: "CHAIN_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface AppError {
  code: ErrorCode;
  message: string;
  statusCode: number;
  details?: Record<string, unknown>;
}
